apiVersion: autoscaling/v2beta2 
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-knote-autoscace
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: v1 
    kind: ReplicationController 
    name: knote 
  minReplicas: 1
  maxReplicas: 3
  metrics: 
  - type: Resource
    resource:
      name: cpu 
      target:
        type: AverageValue 
        averageValue: 50
